import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  // Generated output is not source and must not be linted. Without this,
  // jest's coverage HTML and the browser-test reports contribute warnings
  // that no one can act on, because the files are regenerated on every run.
  {
    ignores: [
      "dist",
      "coverage",
      "playwright-report",
      "test-results",
      "node_modules",
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": [
        "warn",
        { allowConstantExport: true },
      ],
      "@typescript-eslint/no-unused-vars": "off",
      // LIT-266: the "is this an uploaded/live clip or a dataset row?" test was
      // implemented inline at 13 call sites across 8 files, in five variants
      // that did not agree - which is why live-recording file resolution had to
      // be fixed panel by panel, one commit at a time. It now lives in
      // `src/lib/audioSelection.ts` (`isUploadedAudio`), with tests.
      //
      // A test can only pin the shared function's behaviour; it cannot stop a
      // 14th inline copy appearing. This rule can. It is the enforcement half
      // of the pair.
      "no-restricted-syntax": [
        "error",
        {
          selector:
            "CallExpression[callee.property.name='includes'][arguments.0.value='live_recording']",
          message:
            "Do not test for a live recording with a path substring. Use isUploadedAudio() or isLiveRecordingFilename() from @/lib/audioSelection.",
        },
        {
          selector:
            "VariableDeclarator[id.name='isUploadedFile'][init.type='LogicalExpression']",
          message:
            "Do not inline the uploaded-vs-dataset predicate. Use isUploadedAudio(selectedFile, dataset) from @/lib/audioSelection.",
        },
      ],
      // Inherited from ECHO 1.0: ~60 pre-existing `any` usages across API
      // response handling and shadcn/ui primitives. Downgraded to a warning
      // rather than fixed blind — proper typing needs each API response
      // shape reviewed, not a mechanical pass. Track as follow-up cleanup.
      "@typescript-eslint/no-explicit-any": "warn",
    },
  },
  {
    // shadcn/ui primitives are vendored, not authored here, and are
    // regenerated by the shadcn CLI. They pair each component with a cva()
    // variants export, which trips the Fast Refresh rule. That rule is about
    // hot-reload ergonomics, not correctness, and editing vendored files to
    // satisfy it would be undone by the next regeneration.
    files: ["src/components/ui/**/*.{ts,tsx}"],
    rules: { "react-refresh/only-export-components": "off" },
  }
);
