import React from 'react';
import { Group, Panel, Separator } from 'react-resizable-panels';
import { useAudio } from '../../contexts/AudioContext';
import { Upload, Waves, BarChart3, Binary } from 'lucide-react';

export const MainViewport: React.FC = () => {
  const { currentAudioFile, setAudioFile, taskStatus, activeModelSelection } = useAudio();

    const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
        if (e.target.files && e.target.files[0]) {
              setAudioFile(e.target.files[0]);
                  }
                    };

                      return (
                                  <div className="flex-1 h-full overflow-hidden bg-background">
                                          <Group orientation="horizontal">
                                        
                                                {/* Left Pane: Audio Ingestion & File Browser */}
                                                        <Panel defaultSize={30} minSize={20}>
                                                                  <div className="h-full border-r border-border p-4 flex flex-col space-y-4">
                                                                              <h2 className="text-sm font-semibold text-gray-300 flex items-center gap-2">
                                                                                            <Upload className="h-4 w-4 text-indigo-400" /> Audio Ingestion
                                                                                                        </h2>
                                                                                                                    <label className="border-2 border-dashed border-border hover:border-indigo-500/50 rounded-xl p-6 flex flex-col items-center justify-center cursor-pointer transition-colors bg-surface/50">
                                                                                                                                  <Upload className="h-8 w-8 text-gray-400 mb-2" />
                                                                                                                                                <span className="text-xs text-gray-300 font-medium">Click to upload waveform (.wav, .mp3)</span>
                                                                                                                                                              <input type="file" accept="audio/*" onChange={handleFileUpload} className="hidden" />
                                                                                                                                                                          </label>
                                                                                                                                                                                      {currentAudioFile && (
                                                                                                                                                                                                    <div className="bg-surface p-3 rounded-lg border border-border">
                                                                                                                                                                                                                    <p className="text-xs text-indigo-300 font-mono truncate">{currentAudioFile.name}</p>
                                                                                                                                                                                                                                    <p className="text-[10px] text-gray-400 mt-1">Status: {taskStatus.toUpperCase()}</p>
                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                </Panel>

                                                                                                                                                                                                                                                                                        <Separator className="w-1 bg-border hover:bg-primary/50 transition-colors cursor-col-resize" />

                                                                                                                                                                                                                                                                                                {/* Center Pane: Active Task Diagnostic Predictions */}
                                                                                                                                                                                                                                                                                                        <Panel defaultSize={45} minSize={30}>
                                                                                                                                                                                                                                                                                                                  <div className="h-full border-r border-border p-4 flex flex-col space-y-4">
                                                                                                                                                                                                                                                                                                                              <h2 className="text-sm font-semibold text-gray-300 flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                            <BarChart3 className="h-4 w-4 text-indigo-400" /> {activeModelSelection} Diagnostic Matrix
                                                                                                                                                                                                                                                                                                                                                        </h2>
                                                                                                                                                                                                                                                                                                                                                                    <div className="flex-1 bg-surface/30 border border-border/60 rounded-xl p-4 flex items-center justify-center">
                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-xs text-gray-500 font-mono">
                                                                                                                                                                                                                                                                                                                                                                                                  {currentAudioFile ? `Ready to execute ${activeModelSelection} inference` : 'Upload audio file to render predictions'}
                                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                              </Panel>

                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Separator className="w-1 bg-border hover:bg-primary/50 transition-colors cursor-col-resize" />

                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Right Pane: Waveform & Saliency Maps */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Panel defaultSize={25} minSize={20}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="h-full p-4 flex flex-col space-y-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h2 className="text-sm font-semibold text-gray-300 flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Waves className="h-4 w-4 text-indigo-400" /> Spectrogram & Saliency
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex-1 bg-surface/30 border border-border/60 rounded-xl p-4 flex flex-col items-center justify-center text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Binary className="h-8 w-8 text-gray-600 mb-2" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="text-xs text-gray-500">XAI Saliency Output Canvas</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Panel>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Group>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        